### ISSUE TITLE
Purpose of exposing "services" objects?

### ISSUE THREAD

**Issue by sicking** [flyweb/spec#1]
The purpose of the "services" objects seems to be to enable services to get added and removed after the initial discovery has happened.

However I don't understand what the UX to drive would look like. My vision had been that when discoverNearbyServices is called, that the browser would display a list of devices that matches the chosen type. But once the user makes a choice that that UX would go away.

Could we instead simply return a list of FlyWebService objects?

We could even let the caller of discoverNearbyServices indicates if it wants to let the user choose multiple devices or not. If the caller only wants one device we'd return a FlyWebService object or null. If multiple devices is enabled, we'd return an array of 1 or more FlyWebService objecs, or null.

**Comment by kannanvijayan-zz** [comment]
I had certain use cases in mind, in particular the situation where the page itself could render an interface to the discovered services, or in certain circumstances, automatically choose a preferred service.

Pages may want to do sophisticated filtering of services, or order them according to some prioritization that is specific to the page.

That said, there are definitely privacy and security issues that come up with exposing the list-of-services to the page directly, instead of just services pre-selected by the user.

I'm personally not hung up on the specific design of the page getting a list of all services, we can change it if we feel strongly that the privacy/security issues are bad.  I originally figured the privacy aspects would be mollified because 1) the user would be prompted to allow the page to scan for services, and 2) the only services that would be returned are specifically fly web services.

**Comment by sicking** [comment]
Ah, yeah, I don't think that we can expose the list of services without
user consent for privacy reasons.

Doing so would enable the page to detect what products that you own by
seeing unique services that they expose. It might even allow figuring out
the user location some cases, the same way that we can figure out your
location based on WiFi networks in range.

(BTW, I'm heading on PTO for a week, so won't be very reachable)

**Comment by kannanvijayan-zz** [comment]
I was thinking that we would still get user consent for discovery, but it would happen at two points.  The interaction would go something like this:
1. Page makes discovery API call.
2. User agent prompts user with indication that page is doing a discovery, presents user with options:
   Accept (allow page to do discovery - page sees all nearby FlyWeb services)
   Accept and remember (allow page to do discovery, and remember the choice)
   Reject (disallow page from doing discovery - API call fails)
   Reject and remember (disallow page from doing discovery, and remember the choice)
   Accept Limited (provide user a list of the services the page is allowed to see).
3. Page gets back list of services (or thrown exception if Reject was chosen)
4. Page chooses a service and initiates a connection to it.
5. User is prompted to about page establishing a connection to a particular service.  Choices are as above:
   Accept, Accept and remember, Reject, Reject and remember

In the second case, "Accept and remember" will let that particular page subsequently connect to that particular service without prompting.

**Comment by sicking** [comment]
I do have concerns with requiring two prompts. I know most developers
really hate prompts so having to have two is likely something that they
want to avoid.

However I agree that there might be interesting use cases for the flow that
you are describing.

How about we have a discovery api, which prompts when called and which
returns an object which contains a updating list of services.

Then have a separate function for directly requesting to connect to a
device.

Both these functions would take a filter parameter, and would let you pass
a device id and/or device type as the filter parameter.

This way the page can do its own discovery if it is OK with two prompts, or
it could just request connections directly if it only wants a single prompt.
